#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MusicCityAnimalRescueManagement;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Accounting/DeleteExpense.cshtml")]
    public partial class _Views_Accounting_DeleteExpense_cshtml : System.Web.Mvc.WebViewPage<MusicCityAnimalRescueManagement.Models.AccountEntries.ExpenseEntry>
    {
        public _Views_Accounting_DeleteExpense_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Accounting\DeleteExpense.cshtml"
  
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Delete</h2>\r\n\r\n<h3>Are you sure you want to delete this?</h3>\r\n<div>\r\n   " +
" <h4>ExpenseEntry</h4>\r\n    <hr />\r\n    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.StrAccountType.AccountTypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.StrAccountType.AccountTypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        ");

WriteLiteral("\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.EffectiveDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.EffectiveDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 40 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.SuppliesDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.SuppliesDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 48 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.SuppliesComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.SuppliesComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.VetBillsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 60 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.VetBillsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 64 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.VetBillsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 68 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.VetBillsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 72 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MedicineDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 76 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.MedicineDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 80 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MedicineComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 84 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.MedicineComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 88 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.InsurancePremiumsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 92 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.InsurancePremiumsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 96 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.InsurancePremiumsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 100 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.InsurancePremiumsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 104 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.FosterReimbursementDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 108 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.FosterReimbursementDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 112 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.FosterReimbursementComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 116 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.FosterReimbursementComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 120 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MiscellaneousExpenseDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 124 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.MiscellaneousExpenseDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 128 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MiscellaneousExpenseComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 132 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.DisplayFor(model => model.MiscellaneousExpenseComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n    </dl>\r\n\r\n");

            
            #line 137 "..\..\Views\Accounting\DeleteExpense.cshtml"
    
            
            #line default
            #line hidden
            
            #line 137 "..\..\Views\Accounting\DeleteExpense.cshtml"
     using (Html.BeginForm()) {
        
            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Accounting\DeleteExpense.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Accounting\DeleteExpense.cshtml"
                                


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-actions no-color\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Delete\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" /> |\r\n");

WriteLiteral("            ");

            
            #line 142 "..\..\Views\Accounting\DeleteExpense.cshtml"
       Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 144 "..\..\Views\Accounting\DeleteExpense.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
