#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MusicCityAnimalRescueManagement;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Accounting/DetailsExpense.cshtml")]
    public partial class _Views_Accounting_DetailsExpense_cshtml : System.Web.Mvc.WebViewPage<MusicCityAnimalRescueManagement.Models.AccountEntries.ExpenseEntry>
    {
        public _Views_Accounting_DetailsExpense_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Accounting\DetailsExpense.cshtml"
  
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Details</h2>\r\n\r\n<div>\r\n    <h4>ExpenseEntry</h4>\r\n    <hr />\r\n    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.StrAccountType.AccountTypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.StrAccountType.AccountTypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.SuppliesDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.SuppliesDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.SuppliesComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.SuppliesComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 39 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.VetBillsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.VetBillsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 47 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.VetBillsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.VetBillsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 55 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MedicineDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 59 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.MedicineDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 63 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MedicineComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 67 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.MedicineComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 71 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.InsurancePremiumsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 75 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.InsurancePremiumsDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 79 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.InsurancePremiumsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 83 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.InsurancePremiumsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 87 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.FosterReimbursementDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 91 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.FosterReimbursementDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 95 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.FosterReimbursementComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 99 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.FosterReimbursementComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 103 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MiscellaneousExpenseDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 107 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.MiscellaneousExpenseDecimal));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 111 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.MiscellaneousExpenseComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 115 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.MiscellaneousExpenseComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 119 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayNameFor(model => model.EffectiveDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 123 "..\..\Views\Accounting\DetailsExpense.cshtml"
       Write(Html.DisplayFor(model => model.EffectiveDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n\r\n    </dl>\r\n</div>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 129 "..\..\Views\Accounting\DetailsExpense.cshtml"
Write(Html.ActionLink("Edit", "EditExpense", new { id = Model.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("    ");

            
            #line 130 "..\..\Views\Accounting\DetailsExpense.cshtml"
Write(Html.ActionLink("Back to List", "Entries"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
